/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import castlecrawler.Stage;
import castlecrawler.Room;
import castlecrawler.EventRoom;
import castlecrawler.EnemyRoom;
import castlecrawler.LootRoom;

/**
 *
 * @author David Cabezas
 */
public class StageView extends javax.swing.JPanel {

    /**
     * Creates new form MapView
     */
    public StageView() {
        initComponents();
       
        revalidate();
        repaint();
    }
    
    void setStage(Stage stage){
        pMap.removeAll();
        Room[][] map = stage.getMap();
        
        Room r;
        RoomView rv= new EmptyRoomView(false, false);
        
        int nR = stage.getNRows();
        int nC = stage.getNCols();
        
        pMap.setLayout(new java.awt.GridLayout(nR, nC));
        for (int i = 0; i < nR; i++){
            for (int j = 0; j < nC; j++){
                r=map[i][j];
                switch (r.getType()){
                    case EVENTROOM:
                        rv = new EventRoomView(r.isVisible(), r.selected());
                        break;
                    case ENEMYROOM:
                        rv = new EnemyRoomView(r.isVisible(), r.selected());
                        ((EnemyRoomView) rv).setEnemyRoom((EnemyRoom)r);
                        break;
                    case LOOTROOM:
                        rv = new LootRoomView(r.isVisible(), r.selected());
                        ((LootRoomView) rv).setLootRoom((LootRoom)r);
                        break;
                    case EMPTYROOM:
                        rv = new EmptyRoomView(r.isVisible(), r.selected());
                        break;
                    case FINALROOM:
                        rv = new FinalRoomView(r.isVisible(), r.selected());
                        break;
                    case STARTROOM:
                        rv = new StartRoomView(r.isVisible(), r.selected());                   
                }
                pMap.add(rv);
            }
        }
        revalidate();
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pMap = new javax.swing.JPanel();

        pMap.setBackground(new java.awt.Color(0, 0, 0));
        pMap.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pMap.setLayout(new java.awt.GridLayout(5, 5));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pMap, javax.swing.GroupLayout.DEFAULT_SIZE, 761, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pMap, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel pMap;
    // End of variables declaration//GEN-END:variables
}
